### ISSUE TITLE
This is cool!! Feature request! 

### ISSUE THREAD

**Issue by 1N50MN14** [Rich-Harris/Statesman#1]
Rich!! You got some goodies in here!! Statesman is awesome as hell!, gonna use this one instead! :-)

Feature request! (which plays well with Anglebars)

It would be GREAT if something like the following was possible:

``` javascript
var observers = state.observe( 'todos.*.completed', function ( newValue, oldValue ) {
   var total = state.get('total_completed');
   total += newValue ? +1 : -1;
   state.set('total_completed', total);
   tpl.update();
});
```

(the above can obviously be achieved as well by setting an observer on every single item)

Check this out: https://github.com/deoxxa/dotty/blob/master/lib/index.js
:-)

**Comment by Rich-Harris** [comment]
Thanks man! I've got you covered! You need to use _computed values_:

``` js
state = new Statesman({ todos: todos });

state.compute( 'completed_todos', {
  trigger: 'todos',
  fn: function ( todos ) {
    return todos.filter( function ( t ) { return t.completed; })
  }
});

state.observe( 'completed_todos.length', function ( num ) {
  alert( num + ' todos completed' );
}, true ); // passing in true here means it fires straight away rather than waiting for a change
```

I thought about doing some kind of wildcard/regex-based observers, but eventually decided against it because it would mean that whenever **any** part of the model changed, all the wildcard patterns would need to be tested (as opposed to just doing property lookups, as at present) which could get slow with a complex model. All of the things I could think of wanting to do with wildcards can be done with computed values, and I believe it's more efficient that way.

I hadn't seen dotty, will check it out, cheers.

Yeah, this is a better tool for overall state management than Anglebars - an Anglebars instance is only really concerned with its own state, whereas this is designed to be central to an app. Of course, you can bind the two together with e.g.

``` js
state.observe( 'todos', function ( todos ) {
  anglebars.set( 'todos', todos );
}, true );
```

(I might come up with a neater syntax for combining the two but don't really know if it's worth it.)

**Comment by 1N50MN14** [comment]
Ah you make valid points! and yeah, not worth the effort combining the two.

PS: I good some goodies coming your way over the weekend :-)
